数组：由numpy支持

# 1 数组的创建

## 1.1 使用np.array()从列表创建

np.array(object,dtype)

- object:指定输入数据
- dtype:指定数据类型,如果未指定则自动判断

In [1]:
import numpy as np

In [2]:
# 一维数组
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
# 二维数组
data = [
    [1,2,3,4,5],
    [2,3,4,5,6],
    [3,4,5,6,7],
]
arr2 = np.array(object=data)
arr2

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

## 1.2 从内置函数创建

### 1.2.1 np.zeros()：全0数组

np.zeros(shape,dtype)

- shape:指定形状，可以是一个数字（一维），也可以是一个元组（多维）
- dtype:数据类型，默认float

In [4]:
np.zeros((2,3),dtype=object)

array([[0, 0, 0],
       [0, 0, 0]], dtype=object)

### 1.2.2 np.ones（）全1数组

参数同全0数组

In [5]:
np.zeros((2,3),dtype='int64')

array([[0, 0, 0],
       [0, 0, 0]])

### 1.2.3 np.full（）：指定数值的数组

np.full(shape,fill_value,dtype)

- shape:形状
- fill_value:元素值
- dtype:类型

In [6]:
np.full((2,2),8,dtype='int64')

array([[8, 8],
       [8, 8]])

### 1.2.4 np.arange():创建连续整数数组

np.arange(start,stop,step,dtype)

- start:起始值，包含，默认0
- stop:结尾值，不含stop
- step:步长
- dtype：默认float

In [8]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

### 1.2.5 np.linspace():创建等间距数值的数组

np.linspace(start,stop,num,dtype)

- start:起始值，包含，默认0
- stop:结尾值，包含stop
- num:生成几个值,不能写数组
- dtype：默认float

In [14]:
np.linspace(1,11,num=10)

array([ 1.        ,  2.11111111,  3.22222222,  4.33333333,  5.44444444,
        6.55555556,  7.66666667,  8.77777778,  9.88888889, 11.        ])


### 1.2.6 创建随机数组

### 1.2.6.1 np.random.randint(low,high,size=())创建随机整数数组

- low:最小值
- high:最大值
- size:生成个数，可以给元组

In [12]:
np.random.randint(1,10,size=(1,2))

array([[6, 2]], dtype=int32)

### 1.2.6.2 np.random.uniform(low,high,size=())创建随机浮点数数数组，其实是均匀分布

- low:最小值
- high:最大值
- size:生成个数，可以给元组

In [15]:
np.random.uniform(1,10,size=(1,2))

array([[4.93565893, 4.77617198]])

### 1.2.6.3 np.random.randn(size)创建符合标准正态分布的数组

均值=0，标准差=1，size表示生成个数

In [16]:
np.random.randn(20)

array([ 1.48019462,  0.59156153,  1.55475728, -0.72439693, -0.19335677,
        1.46059167, -0.14510095, -0.36072715, -1.67054808, -0.01845591,
       -0.55125611, -0.29051469, -1.39497785,  0.54349729, -2.33452124,
       -1.12366626,  2.18202925, -1.43644259,  0.13138597,  0.02485985])


#### 1.2.6.4 np.random.permutation(arr)对数组随机打乱排列

In [17]:
arr1 = np.array([1,2,3,4,5])
np.random.permutation(arr1)

array([2, 5, 1, 3, 4])

# 2 数组的属性

In [21]:
arr2 = [
    [1,2,3,4,5],
    [2,3,4,5,6],
]
arr2 = np.array(arr2)

## 2.1 .shape查看数组形状


In [22]:
arr2.shape

(2, 5)

## 2.2 .size查看数组元素的总个数

In [23]:
arr2.size

10

## 2.3 .dtype查看数组中元素数据类型

In [24]:
arr2.dtype

dtype('int64')


# 3 数组的主要方法

## 3.1 数组索引与访问

### 3.1.1 一维数组索引,从0开始


In [26]:
arr3 = np.array([1,2,3,4,5,6,7,8])
arr1[3]

np.int64(4)

### 3.1.2 二维数组索引

类似列表和DataFrame，可以切片

In [27]:
arr2 = [
    [1,2,3,4,5],
    [2,3,4,5,6],
]
arr2 = np.array(arr2)

arr2[0,1:4:2]

array([2, 4])

### 3.1.3 条件选择，在索引中使用布尔表达式,符合条件的值整理成一个一维数组返回

In [29]:
arr2[arr2 > 3]

array([4, 5, 4, 5, 6])

In [30]:
# 是一个布尔值数组
arr2 > 3

array([[False, False, False,  True,  True],
       [False, False,  True,  True,  True]])


## 3.2 数组运算

### 3.2.1 元素级运算，分别对每个元素生效

In [31]:
arr2 = [
    [1,2,3,4,5],
    [2,3,4,5,6],
]
arr2 = np.array(arr2)
arr2 + 10

array([[11, 12, 13, 14, 15],
       [12, 13, 14, 15, 16]])

### 3.2.2 数组间运算，对应位置的元素进行运算


In [32]:
arr3 = [
    [1,2,3,4,5],
    [2,3,4,5,6],
]
arr2 + arr3

array([[ 2,  4,  6,  8, 10],
       [ 4,  6,  8, 10, 12]])

### 3.2.3 广播机制

数组形状不一样但兼容时，自动扩展小数组以匹配形状,如果一边长一边短不能广播,满足以下条件才可以：

简单理解：对两个数组，分别比较他们的每一个维度（若其中一个数组没有当前维度则忽略），满足：

- 数组拥有相同形状。
- 当前维度的值相等。
- 当前维度的值有一个是 1。
-
若条件不满足，抛出 "ValueError: frames are not aligned" 异常。


In [33]:
arr4 = [
    [1,2,3],
    [2,3,4],
    [3,8,1]
]
arr4 = np.array(arr4)

In [38]:
# 3*3和2*5，失败
# arr4 + arr3
arr5 = np.array([
    [1,2,3],
]
)
# 3*3 和1*3 成功
arr4 + arr5

array([[ 2,  4,  6],
       [ 3,  5,  7],
       [ 4, 10,  4]])

## 3.3 数组中统计值计算

类似dataFrame,不过不分行列，所有数值全部纳入计算

- arr.sum():
- arr.mean():
- arr.max():
- arr.min():
- arr.std():
- arr.var():
-

In [39]:
arr4.sum()

np.int64(27)

## 3.4 数组形状修改

### 3.4.1 arr.reshape(v1,v2):修改形状


In [41]:
arr4 = [
    [1,2,3],
    [2,3,4],
]
arr4 = np.array(arr4)


arr4.reshape(3,2)

array([[1, 2],
       [3, 2],
       [3, 4]])

### 3.4.2 .ravel()：数组展平成一维数组



In [42]:
arr4.ravel()

array([1, 2, 3, 2, 3, 4])

## 3.5 数组合并与分割


### 3.5.1 np.concatenate([arr1,arr2],axis=0)数组合并


In [46]:
arr4 = [
    [1,2,3],
    [2,3,4],
    [3,8,1]
]
arr4 = np.array(arr4)

arr2 = [
    [1,2,3,4,5],
    [2,3,4,5,6],
    [2,3,4,5,6],
]
arr2 = np.array(arr2)

np.concatenate([arr4,arr2],axis=1)

array([[1, 2, 3, 1, 2, 3, 4, 5],
       [2, 3, 4, 2, 3, 4, 5, 6],
       [3, 8, 1, 2, 3, 4, 5, 6]])

### 3.5.2 np.split(arr1,arr2,num)数组分割，平均分为3组

In [50]:
# 对数量没要求的
np.array_split(arr2, 3)
# 按从左到右，从上到下的顺序拆，需要正好能均分
np.split(arr2,3)
# 按列拆
np.hsplit(arr2, 5)
# 按行拆
np.hsplit(arr2, 3)
# 按深度，拆三维的
# np.dsplit(arr2, 3)

[array([[1],
        [2],
        [2]]),
 array([[2],
        [3],
        [3]]),
 array([[3],
        [4],
        [4]]),
 array([[4],
        [5],
        [5]]),
 array([[5],
        [6],
        [6]])]